name: Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['linux', 'windows']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Define enviroment
        shell: bash
        run: |
          tagname=$(git describe --tags --abbrev=0)
          echo "version=$tagname"
          echo "version=$tagname" >> $GITHUB_ENV
          release="EmailKit-$tagname-${{ matrix.target }}"          
          echo "release=$release"
          echo "release=$release" >> $GITHUB_ENV
            
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            echo "filename=$release.zip"
            echo "filename=$release.zip" >> $GITHUB_ENV
          else
            echo "filename=$release.tar.gz"
            echo "filename=$release.tar.gz" >> $GITHUB_ENV
          fi

      - name: Build
        shell: bash
        run: |
          # Build everything
          dotnet publish EmailKit/EmailKit.csproj --framework netcoreapp3.1 --runtime "${{ matrix.target }}" -c Release -o "${{ env.release }}"

          # Pack files
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            # Pack to zip for Windows
            7z a -tzip "${{ env.filename }}" "./${{ env.release }}/*"
          else
            tar czvf "${{ env.filename }}" "${{ env.release }}"
          fi

          # Delete output directory
          rm -r "${{ env.release }}"

      - name: Publish
        id: publish
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: ${{ env.filename }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
